### PR TITLE
Debug

### PR DESCRIPTION
**Pull request by manasij7479**

### CODE REVIEW

**Comment by amhndu** [comment]
We can't link X11 directly, Prattle is supposed to be cross-platform

**Comment by manasij7479** [comment]
@amhndu  True, if you are building it on windows, could you make it conditional ?

**Comment by texus** [comment]
```
if(SFML_OS_LINUX)
    target_link_libraries(prattle-client ${TGUI_LIBRARY} ${SFML_LIBRARIES} X11)
else()
    target_link_libraries(prattle-client ${TGUI_LIBRARY} ${SFML_LIBRARIES})
endif()
```

But don't forget the following line in the cmake script (and copy the file from sfml!) otherwise it doesn't work (just like line 19 already doesn't work since these variables are still undefined).
```
include("${CMAKE_CURRENT_SOURCE_DIR}/cmake/Config.cmake")
```

But it doesn't really matter that it contains linux-only code. If you don't test it regularly on different platforms you will get into problems anyway when trying it out on that platform. Since this is a very early version of the cmake script, it doesn't really has to work on windows yet.

Who is even using windows? :smile:

**Comment by amhndu** [comment]
I'm not building on Windows either, I just wanted the cmake script to be compatible with Windows/other OSs.
I can't make it conditional now, since I'm on my phone atm. I guess, it's fine now, it could be fixed later.

**Comment by amhndu** [comment]
Disregard my above comment, I didn't see texus' comment.

**Comment by TheIllusionistMirage** [comment]
> Who is even using windows? :smile:
Yeah, but still for the sake of it, considering many SFML coders use Windows, we'd have to get Prattle on Windows too :)

**Pull request merged**
